onlineretreatmanager/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_view
from django.contrib.auth import views as auth_view

urlpatterns = [
    path("register/", user_view.register, name="register"),
    path("", include("usermanagement.urls")),
    path('admin/', admin.site.urls),
    path("login/", auth_view.LoginView.as_view(template_name = "users/login.html"), name="login"),
    path("logout/", user_view.log_out, name="logout"),
    path("profile/", user_view.profile , name="profile"),
    path("landing/", user_view.landing_page, name="landing"),
]

usermanagement/urls.py
from . import views
from django.urls import path

app_name = 'usermanagement'

urlpatterns = [
    path("dashboard/", views.user_dashboard, name="dashboard"),
    path("", views.user_dashboard, name="dashboard"),
    # retreat/1/
    path("retreat/<int:retreat_id>/", views.retreat_details, name="retreat_details"),
    path("retreat/<int:retreat_id>/recordings/", views.retreat_recordings, name="retreat_recordings"),
    path("retreat/<int:retreat_id>/resources/", views.retreat_resources, name="retreat_resources"),
]

usermanagement/models.py
from django.db import models

class Retreat(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField("start_date")
    end_date = models.DateTimeField("end_date")
    description = models.CharField(max_length=1200, blank= True)
    schedule = models.TextField(blank=True)
    zoom_link = models.URLField(blank=True)
    retreat_image = models.URLField(default="https://vh1220.z2systems.com/neon/resource/vh1220/images/buddhalei3(2).JPG")
    announcement = models.TextField(blank=True)

    def __str__(self):
        return self.name    

class Teacher(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=1200, blank= True)

    def __str__(self):
        return self.name


class Recording(models.Model):
    retreat = models.ForeignKey(Retreat, on_delete=models.CASCADE, default= 1 )
    name = models.CharField(max_length=200)
    time = models.DateTimeField("recording_time")
    recording_link = models.URLField(max_length=200)

    def __str__(self):
        return self.name


class Resource(models.Model):
    retreat = models.ForeignKey(Retreat, on_delete = models.CASCADE, default= 1 )
    name = models.CharField(max_length=200)
    resoruce_link = models.URLField(max_length=200)

    def __str__(self):
        return self.name

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    # Configuration
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

usermanagement/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Retreat, Recording, Resource
from django.contrib.auth.decorators import login_required

@login_required(login_url='login')
def user_dashboard(request):
    retreat_list = Retreat.objects.all()
    context = {
        'retreat_list' : retreat_list,
    }
    return render(request,'usermanagement/retreat.html', context )


@login_required(login_url='login')
def retreat_details(request, retreat_id):
    retreat_detail = Retreat.objects.get(pk=retreat_id)
    context = {
        'retreat_detail': retreat_detail,
    }
    return render(request,'usermanagement/retreat_detail.html', context )

@login_required(login_url='login')
def retreat_recordings(request, retreat_id):
    recordings = Recording.objects.filter(retreat=retreat_id).values()
    context = {
        'recordings': recordings,
        'retreat_id': retreat_id,
    }
    return render(request,'usermanagement/recordings.html', context )


def retreat_resources(request, retreat_id):
    resources = Resource.objects.filter(retreat= retreat_id).values()
    context = {
        'resources': resources,
        'retreat_id': retreat_id
    }
    return render(request, 'usermanagement/resources.html', context  )

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from .forms import RegisterForm

# Create your views here.
def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('usermanagement:dashboard')
            
    else:
        form = RegisterForm()
        return render(request, 'users/register.html', {'form': form})

@login_required
def profile(request):
    return render(request, 'users/profile.html')

@login_required
def log_out(request):
    logout(request)
    return redirect('login')


def landing_page(request):
    return render(request, 'users/landing.html')

    

usermanagement/templates/usermanagement/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>VH</title>
    {% load static %}
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
    <link rel="stylesheet" href="{% static 'usermanagement/style.css' %}" />
  </head>
  <body>
    {% block content %}{% endblock %}
  </body>
</html>

usermanagement/templates/usermanagement/recordings.html
{% extends "usermanagement/base.html" %} {% block content %}
<nav class="navbar navbar-light bg-warning mb-4">
  <a
    class="navbar-brand"
    href="{% url 'usermanagement:retreat_details' retreat_id %}"
  >
    VH
  </a>
  <div class="navbar">
    <a
      class="nav-item nav-link"
      href="{% url 'usermanagement:retreat_details' retreat_id %}"
      >Schedule</a
    >
    <a
      class="nav-item nav-link"
      href="{% url 'usermanagement:retreat_recordings' retreat_id %}"
      >Recordings</a
    >
    <a class="nav-item nav-link" href="#">Resources</a>
    {% if user.is_authenticated %}
    <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
    {% endif %}
  </div>
</nav>
<div class="container">
  <div class="row">
    <table class="table table-bordered caption-top">
      <caption>
        Retreat recordings
      </caption>
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Time</th>
          <th scope="col">Recording Link</th>
        </tr>
      </thead>
      <tbody>
        {% for recording in recordings %}
        <tr>
          <td>{{recording.name}}</td>
          <td>{{recording.time}}</td>
          <td><a href="{{recording.recording_link}}"> ▶️ </a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  {% endblock content %}
</div>

usermanagement/templates/usermanagement/resources.html
{% extends "usermanagement/base.html" %} {% block content %}
<h2>Resources working</h2>
{% endblock content %}

usermanagement/templates/usermanagement/retreat.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Document</title>
    {% load static %}
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'usermanagement/style.css' %}"
    />
  </head>
  <body>
    {% for retreat in retreat_list %}
    <div class="container my-5">
      <div class="row retreat">
        <div class="col-6">
          <h2>{{retreat.start_date}} - {{retreat.end_date}}</h2>
        </div>
        <div class="col"><h1>{{retreat.name}}</h1></div>
        <div class="col">
          <a
            class="btn btn-success"
            href="{% url 'usermanagement:retreat_details' retreat.id %}"
            >Details
          </a>
        </div>
      </div>
    </div>
    {% endfor %}
  </body>
</html>

usermanagement/templates/usermanagement/retreat_detail.html
{% extends "usermanagement/base.html" %} {% block content %}
<nav class="navbar navbar-light bg-warning mb-4">
  <a class="navbar-brand" href="{% url 'usermanagement:retreat_details' retreat_detail.id %}"> VH </a>
  <div class="navbar">
    <a
      class="nav-item nav-link"
      href="{% url 'usermanagement:retreat_details' retreat_detail.id %}"
      >Schedule</a>
    <a
      class="nav-item nav-link"
      href="{% url 'usermanagement:retreat_recordings' retreat_detail.id %}"
      >Recordings</a
    >
    <a class="nav-item nav-link"    href="{% url 'usermanagement:retreat_resources' retreat_detail.id %}"
    >Resources</a>
    {% if user.is_authenticated %}
    <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
    {% endif %}
  </div>
</nav>
<div class="container">
  <div class="row">
    <div class="col-8 col-sm-8 gx-5">
      <h2>{{retreat_detail.name}}</h2>
      <h4>{{retreat_detail.description}}</h4>
      <table class="table table-bordered caption-top">
        <caption>
          Saturday and Sunday Schedule
        </caption>
        <thead>
          <tr>
            <th scope="col">Timings</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>4am</td>
            <td>Sitting Meditation</td>
          </tr>
          <tr>
            <td>6am</td>
            <td>Walking Meditation</td>
          </tr>
          <tr>
            <td>7am</td>
            <td>Sitting Meditation</td>
          </tr>
          <tr>
            <td>10am</td>
            <td>Sitting with Instructions</td>
          </tr>
          <tr>
            <td>11am</td>
            <td>Q &amp A Session</td>
          </tr>
          <tr>
            <td>2pm</td>
            <td>Dhamma Talk</td>
          </tr>
          <tr>
            <td>4pm</td>
            <td>Metta Chanting and Sit</td>
          </tr>
        </tbody>
      </table>

      <h2>Zoom details</h2>
      <h4>
        <a href="{{retreat_detail.zoom_link}}"
          >Click here to join the meeting
        </a>
      </h4>

    </div>
    <div class="col-4">
      <h2>Announcements</h2>
      <h4>{{retreat_detail.announcement}}</h4>
    </div>
    </div>
  </div>

  <div class="row">
    <div class="col-8 col-sm-8 mx-5">
   
    </div>
  </div>

  {% endblock content %}
</div>

users/templates/users/landing.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>VH Online Retreat</title>
    {% load static %}
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
    <link rel="stylesheet" href="{% static 'usermanagement/style.css' %}" />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-warning mb-4">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">VH</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Dropdown
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider" /></li>
                <li>
                  <a class="dropdown-item" href="#">Something else here</a>
                </li>
              </ul>
            </li>
            <li class="nav-item">
              <a
                class="nav-link disabled"
                href="#"
                tabindex="-1"
                aria-disabled="true"
                >Disabled</a
              >
            </li>
          </ul>
          <form class="d-flex">
            <input
              class="form-control me-2"
              type="search"
              placeholder="Search"
              aria-label="Search"
            />
            <button class="btn btn-outline-success" type="submit">
              Search
            </button>
          </form>
        </div>
      </div>
    </nav>
  </body>
</html>

users/templates/users/login.html
<form method="POST">
  {% csrf_token %} {{form}}
  <button type="submit">Login</button>
</form>

users/templates/users/profile.html
<h1>{{user.username}}</h1>

users/templates/users/register.html
<form method="POST">
  {% csrf_token %} {{form}}
  <button type="submit" class="btn btn-primary">Sign up</button>
</form>